using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TheSharpFactory.Entity.MainDb.Media;
using TheSharpFactory.Repository.Container.Interfaces;

namespace TheSharpFactory.Web.Areas.Media.Controllers
{
    [Area("Media")]
    public class PlaylistsController : Controller
    {
        //reference to the repository generated by The Sharp Factory
        private readonly IRepositoryContainer _repository;

        public PlaylistsController(IRepositoryContainer repository)
        {
            _repository = repository;
        }

        // GET: PlaylistsController
        public ActionResult Index()
        {
            var model = _repository.MainDb.Media.Playlist.ToList();

            return View(model);
        }

        // GET: PlaylistsController/Details/5
        public ActionResult Details(int id)
        {
            var model = _repository.MainDb.Media.Playlist.ByPK(id);

            return View(model);
        }

        // GET: PlaylistsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PlaylistsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Playlist playlist)
        {
            _repository.MainDb.Media.Playlist.Create(playlist);

            return RedirectToAction(nameof(Index));
        }

        // GET: PlaylistsController/Edit/5
        public ActionResult Edit(int id)
        {
            var model = _repository.MainDb.Media.Playlist.ByPK(id);

            return View(model);
        }

        // POST: PlaylistsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Playlist playlist)
        {
            _repository.MainDb.Media.Playlist.Update(playlist);

            var model = _repository.MainDb.Media.Playlist.ByPK(playlist.PlaylistId);

            //return View(model);
            return RedirectToAction(nameof(Index));
        }

        // GET: PlaylistsController/Delete/5
        public ActionResult Delete(int id)
        {
            var model = _repository.MainDb.Media.Playlist.ByPK(id);

            return View(model);
        }

        // POST: PlaylistsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Playlist playlist)
        {
            _repository.MainDb.Media.Playlist.Delete(playlist);

            return RedirectToAction(nameof(Index));
        }
    }
}
