/*SFF*/
/************************************************
This class has been generated dynamically.
Any changes you make here will be overwritten.
To add your own code create a partial class
in a sepparate file.
with the following declaration:

namespace TheSharpFactory.Query
{
    internal static partial class Lookup
    {
    }
}

************************************************/

using System;
using System.Collections.Generic;
using System.Xml.Linq;
using MainDbE = TheSharpFactory.Entity.MainDb;

namespace TheSharpFactory.Query
{

    /// <summary>
    /// This class contains infrastructure information used by the Filter classes.
    /// </summary>
    internal static partial class Lookup
    {
        //key is MetadataToken of the PropEnum type, the value is a Hashset of ints that represent the int value of the PropEnum choice.
        #region NullableProps
        internal static readonly Dictionary<int, HashSet<int>> NullableProps = new Dictionary<int, HashSet<int>>(93)
        {
            {typeof(MainDbE.Accounting.InvoiceProperty).MetadataToken, new HashSet<int>(9){(int)MainDbE.Accounting.InvoiceProperty.BillingAddress,(int)MainDbE.Accounting.InvoiceProperty.BillingCity,(int)MainDbE.Accounting.InvoiceProperty.BillingState,(int)MainDbE.Accounting.InvoiceProperty.BillingCountry,(int)MainDbE.Accounting.InvoiceProperty.BillingPostalCode,}},
            {typeof(MainDbE.Accounting.InvoiceLineProperty).MetadataToken, new HashSet<int>(5){}},
            {typeof(MainDbE.Accounting.OrderDetailProperty).MetadataToken, new HashSet<int>(3){}},
            {typeof(MainDbE.Media.AlbumProperty).MetadataToken, new HashSet<int>(3){}},
            {typeof(MainDbE.Media.ArtistProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.GenreProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.MediaTypeProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.PlaylistProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.PlaylistTrackProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.TrackProperty).MetadataToken, new HashSet<int>(9){(int)MainDbE.Media.TrackProperty.AlbumId,(int)MainDbE.Media.TrackProperty.GenreId,(int)MainDbE.Media.TrackProperty.Composer,(int)MainDbE.Media.TrackProperty.Bytes,}},
            {typeof(MainDbE.People.CustomerProperty).MetadataToken, new HashSet<int>(13){(int)MainDbE.People.CustomerProperty.Company,(int)MainDbE.People.CustomerProperty.Address,(int)MainDbE.People.CustomerProperty.City,(int)MainDbE.People.CustomerProperty.State,(int)MainDbE.People.CustomerProperty.Country,(int)MainDbE.People.CustomerProperty.PostalCode,(int)MainDbE.People.CustomerProperty.Phone,(int)MainDbE.People.CustomerProperty.Fax,(int)MainDbE.People.CustomerProperty.SupportRepId,}},
            {typeof(MainDbE.People.EmployeeProperty).MetadataToken, new HashSet<int>(15){(int)MainDbE.People.EmployeeProperty.Title,(int)MainDbE.People.EmployeeProperty.ReportsTo,(int)MainDbE.People.EmployeeProperty.BirthDate,(int)MainDbE.People.EmployeeProperty.HireDate,(int)MainDbE.People.EmployeeProperty.Address,(int)MainDbE.People.EmployeeProperty.City,(int)MainDbE.People.EmployeeProperty.State,(int)MainDbE.People.EmployeeProperty.Country,(int)MainDbE.People.EmployeeProperty.PostalCode,(int)MainDbE.People.EmployeeProperty.Phone,(int)MainDbE.People.EmployeeProperty.Fax,(int)MainDbE.People.EmployeeProperty.Email,}},
            {typeof(MainDbE.Accounting.CheckInvoice_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Accounting.CheckInvoice_RequestProperty.InvoiceId,}},
            {typeof(MainDbE.Accounting.CheckInvoiceLine_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Accounting.CheckInvoiceLine_RequestProperty.InvoiceLineId,}},
            {typeof(MainDbE.Accounting.DeleteInvoice_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Accounting.DeleteInvoice_RequestProperty.InvoiceId,}},
            {typeof(MainDbE.Accounting.DeleteInvoiceLine_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Accounting.DeleteInvoiceLine_RequestProperty.InvoiceLineId,}},
            {typeof(MainDbE.Accounting.GetInvoice_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Accounting.GetInvoice_RequestProperty.InvoiceId,}},
            {typeof(MainDbE.Accounting.GetInvoiceLine_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Accounting.GetInvoiceLine_RequestProperty.InvoiceLineId,}},
            {typeof(MainDbE.Accounting.GetInvoiceLinesByInvoice_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Accounting.GetInvoiceLinesByInvoice_RequestProperty.InvoiceId,}},
            {typeof(MainDbE.Accounting.GetInvoiceLinesByTrack_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Accounting.GetInvoiceLinesByTrack_RequestProperty.TrackId,}},
            {typeof(MainDbE.Accounting.GetInvoicesByCustomer_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Accounting.GetInvoicesByCustomer_RequestProperty.CustomerId,}},
            {typeof(MainDbE.Accounting.GetInvoicesByEmployee_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Accounting.GetInvoicesByEmployee_RequestProperty.EmployeeId,}},
            {typeof(MainDbE.Accounting.InsertInvoice_RequestProperty).MetadataToken, new HashSet<int>(9){(int)MainDbE.Accounting.InsertInvoice_RequestProperty.CustomerId,(int)MainDbE.Accounting.InsertInvoice_RequestProperty.InvoiceDate,(int)MainDbE.Accounting.InsertInvoice_RequestProperty.BillingAddress,(int)MainDbE.Accounting.InsertInvoice_RequestProperty.BillingCity,(int)MainDbE.Accounting.InsertInvoice_RequestProperty.BillingState,(int)MainDbE.Accounting.InsertInvoice_RequestProperty.BillingCountry,(int)MainDbE.Accounting.InsertInvoice_RequestProperty.BillingPostalCode,(int)MainDbE.Accounting.InsertInvoice_RequestProperty.Total,(int)MainDbE.Accounting.InsertInvoice_RequestProperty.InvoiceId,}},
            {typeof(MainDbE.Accounting.InsertInvoiceLine_RequestProperty).MetadataToken, new HashSet<int>(5){(int)MainDbE.Accounting.InsertInvoiceLine_RequestProperty.InvoiceId,(int)MainDbE.Accounting.InsertInvoiceLine_RequestProperty.TrackId,(int)MainDbE.Accounting.InsertInvoiceLine_RequestProperty.UnitPrice,(int)MainDbE.Accounting.InsertInvoiceLine_RequestProperty.Quantity,(int)MainDbE.Accounting.InsertInvoiceLine_RequestProperty.InvoiceLineId,}},
            {typeof(MainDbE.Accounting.UpdateInvoice_RequestProperty).MetadataToken, new HashSet<int>(9){(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.InvoiceId,(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.CustomerId,(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.InvoiceDate,(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.BillingAddress,(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.BillingCity,(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.BillingState,(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.BillingCountry,(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.BillingPostalCode,(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.Total,}},
            {typeof(MainDbE.Accounting.UpdateInvoiceLine_RequestProperty).MetadataToken, new HashSet<int>(5){(int)MainDbE.Accounting.UpdateInvoiceLine_RequestProperty.InvoiceLineId,(int)MainDbE.Accounting.UpdateInvoiceLine_RequestProperty.InvoiceId,(int)MainDbE.Accounting.UpdateInvoiceLine_RequestProperty.TrackId,(int)MainDbE.Accounting.UpdateInvoiceLine_RequestProperty.UnitPrice,(int)MainDbE.Accounting.UpdateInvoiceLine_RequestProperty.Quantity,}},
            {typeof(MainDbE.Media.CheckAlbum_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.CheckAlbum_RequestProperty.AlbumId,}},
            {typeof(MainDbE.Media.CheckArtist_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.CheckArtist_RequestProperty.ArtistId,}},
            {typeof(MainDbE.Media.CheckGenre_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.CheckGenre_RequestProperty.GenreId,}},
            {typeof(MainDbE.Media.CheckMediaType_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.CheckMediaType_RequestProperty.MediaTypeId,}},
            {typeof(MainDbE.Media.CheckPlaylist_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.CheckPlaylist_RequestProperty.PlaylistId,}},
            {typeof(MainDbE.Media.CheckPlaylistTrack_RequestProperty).MetadataToken, new HashSet<int>(2){(int)MainDbE.Media.CheckPlaylistTrack_RequestProperty.PlaylistId,(int)MainDbE.Media.CheckPlaylistTrack_RequestProperty.TrackId,}},
            {typeof(MainDbE.Media.CheckTrack_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.CheckTrack_RequestProperty.TrackId,}},
            {typeof(MainDbE.Media.DeleteAlbum_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.DeleteAlbum_RequestProperty.AlbumId,}},
            {typeof(MainDbE.Media.DeleteArtist_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.DeleteArtist_RequestProperty.ArtistId,}},
            {typeof(MainDbE.Media.DeleteGenre_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.DeleteGenre_RequestProperty.GenreId,}},
            {typeof(MainDbE.Media.DeleteMediaType_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.DeleteMediaType_RequestProperty.MediaTypeId,}},
            {typeof(MainDbE.Media.DeletePlaylist_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.DeletePlaylist_RequestProperty.PlaylistId,}},
            {typeof(MainDbE.Media.DeletePlaylistTrack_RequestProperty).MetadataToken, new HashSet<int>(2){(int)MainDbE.Media.DeletePlaylistTrack_RequestProperty.PlaylistId,(int)MainDbE.Media.DeletePlaylistTrack_RequestProperty.TrackId,}},
            {typeof(MainDbE.Media.DeleteTrack_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.DeleteTrack_RequestProperty.TrackId,}},
            {typeof(MainDbE.Media.GetAlbum_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.GetAlbum_RequestProperty.AlbumId,}},
            {typeof(MainDbE.Media.GetAlbumsByArtist_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.GetAlbumsByArtist_RequestProperty.ArtistId,}},
            {typeof(MainDbE.Media.GetArtist_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.GetArtist_RequestProperty.ArtistId,}},
            {typeof(MainDbE.Media.GetGenre_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.GetGenre_RequestProperty.GenreId,}},
            {typeof(MainDbE.Media.GetMediaType_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.GetMediaType_RequestProperty.MediaTypeId,}},
            {typeof(MainDbE.Media.GetPlaylist_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.GetPlaylist_RequestProperty.PlaylistId,}},
            {typeof(MainDbE.Media.GetPlaylistsByTrack_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.GetPlaylistsByTrack_RequestProperty.TrackId,}},
            {typeof(MainDbE.Media.GetPlaylistTrack_RequestProperty).MetadataToken, new HashSet<int>(2){(int)MainDbE.Media.GetPlaylistTrack_RequestProperty.PlaylistId,(int)MainDbE.Media.GetPlaylistTrack_RequestProperty.TrackId,}},
            {typeof(MainDbE.Media.GetTrack_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.GetTrack_RequestProperty.TrackId,}},
            {typeof(MainDbE.Media.GetTracksByAlbum_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.GetTracksByAlbum_RequestProperty.AlbumId,}},
            {typeof(MainDbE.Media.GetTracksByArtist_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.GetTracksByArtist_RequestProperty.ArtistId,}},
            {typeof(MainDbE.Media.GetTracksByGenre_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.GetTracksByGenre_RequestProperty.GenreId,}},
            {typeof(MainDbE.Media.GetTracksByInvoice_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.GetTracksByInvoice_RequestProperty.InvoiceId,}},
            {typeof(MainDbE.Media.GetTracksByMediaType_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.GetTracksByMediaType_RequestProperty.MediaTypeId,}},
            {typeof(MainDbE.Media.GetTracksByPlaylist_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.Media.GetTracksByPlaylist_RequestProperty.PlaylistId,}},
            {typeof(MainDbE.Media.InsertAlbum_RequestProperty).MetadataToken, new HashSet<int>(3){(int)MainDbE.Media.InsertAlbum_RequestProperty.Title,(int)MainDbE.Media.InsertAlbum_RequestProperty.ArtistId,(int)MainDbE.Media.InsertAlbum_RequestProperty.AlbumId,}},
            {typeof(MainDbE.Media.InsertArtist_RequestProperty).MetadataToken, new HashSet<int>(2){(int)MainDbE.Media.InsertArtist_RequestProperty.Name,(int)MainDbE.Media.InsertArtist_RequestProperty.ArtistId,}},
            {typeof(MainDbE.Media.InsertGenre_RequestProperty).MetadataToken, new HashSet<int>(2){(int)MainDbE.Media.InsertGenre_RequestProperty.Name,(int)MainDbE.Media.InsertGenre_RequestProperty.GenreId,}},
            {typeof(MainDbE.Media.InsertMediaType_RequestProperty).MetadataToken, new HashSet<int>(2){(int)MainDbE.Media.InsertMediaType_RequestProperty.Name,(int)MainDbE.Media.InsertMediaType_RequestProperty.MediaTypeId,}},
            {typeof(MainDbE.Media.InsertPlaylist_RequestProperty).MetadataToken, new HashSet<int>(2){(int)MainDbE.Media.InsertPlaylist_RequestProperty.Name,(int)MainDbE.Media.InsertPlaylist_RequestProperty.PlaylistId,}},
            {typeof(MainDbE.Media.InsertPlaylistTrack_RequestProperty).MetadataToken, new HashSet<int>(2){(int)MainDbE.Media.InsertPlaylistTrack_RequestProperty.PlaylistId,(int)MainDbE.Media.InsertPlaylistTrack_RequestProperty.TrackId,}},
            {typeof(MainDbE.Media.InsertTrack_RequestProperty).MetadataToken, new HashSet<int>(9){(int)MainDbE.Media.InsertTrack_RequestProperty.Name,(int)MainDbE.Media.InsertTrack_RequestProperty.AlbumId,(int)MainDbE.Media.InsertTrack_RequestProperty.MediaTypeId,(int)MainDbE.Media.InsertTrack_RequestProperty.GenreId,(int)MainDbE.Media.InsertTrack_RequestProperty.Composer,(int)MainDbE.Media.InsertTrack_RequestProperty.Milliseconds,(int)MainDbE.Media.InsertTrack_RequestProperty.Bytes,(int)MainDbE.Media.InsertTrack_RequestProperty.UnitPrice,(int)MainDbE.Media.InsertTrack_RequestProperty.TrackId,}},
            {typeof(MainDbE.Media.UpdateAlbum_RequestProperty).MetadataToken, new HashSet<int>(3){(int)MainDbE.Media.UpdateAlbum_RequestProperty.AlbumId,(int)MainDbE.Media.UpdateAlbum_RequestProperty.Title,(int)MainDbE.Media.UpdateAlbum_RequestProperty.ArtistId,}},
            {typeof(MainDbE.Media.UpdateArtist_RequestProperty).MetadataToken, new HashSet<int>(2){(int)MainDbE.Media.UpdateArtist_RequestProperty.ArtistId,(int)MainDbE.Media.UpdateArtist_RequestProperty.Name,}},
            {typeof(MainDbE.Media.UpdateGenre_RequestProperty).MetadataToken, new HashSet<int>(2){(int)MainDbE.Media.UpdateGenre_RequestProperty.GenreId,(int)MainDbE.Media.UpdateGenre_RequestProperty.Name,}},
            {typeof(MainDbE.Media.UpdateMediaType_RequestProperty).MetadataToken, new HashSet<int>(2){(int)MainDbE.Media.UpdateMediaType_RequestProperty.MediaTypeId,(int)MainDbE.Media.UpdateMediaType_RequestProperty.Name,}},
            {typeof(MainDbE.Media.UpdatePlaylist_RequestProperty).MetadataToken, new HashSet<int>(2){(int)MainDbE.Media.UpdatePlaylist_RequestProperty.PlaylistId,(int)MainDbE.Media.UpdatePlaylist_RequestProperty.Name,}},
            {typeof(MainDbE.Media.UpdatePlaylistTrack_RequestProperty).MetadataToken, new HashSet<int>(2){(int)MainDbE.Media.UpdatePlaylistTrack_RequestProperty.PlaylistId,(int)MainDbE.Media.UpdatePlaylistTrack_RequestProperty.TrackId,}},
            {typeof(MainDbE.Media.UpdateTrack_RequestProperty).MetadataToken, new HashSet<int>(9){(int)MainDbE.Media.UpdateTrack_RequestProperty.TrackId,(int)MainDbE.Media.UpdateTrack_RequestProperty.Name,(int)MainDbE.Media.UpdateTrack_RequestProperty.AlbumId,(int)MainDbE.Media.UpdateTrack_RequestProperty.MediaTypeId,(int)MainDbE.Media.UpdateTrack_RequestProperty.GenreId,(int)MainDbE.Media.UpdateTrack_RequestProperty.Composer,(int)MainDbE.Media.UpdateTrack_RequestProperty.Milliseconds,(int)MainDbE.Media.UpdateTrack_RequestProperty.Bytes,(int)MainDbE.Media.UpdateTrack_RequestProperty.UnitPrice,}},
            {typeof(MainDbE.People.CheckCustomer_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.People.CheckCustomer_RequestProperty.CustomerId,}},
            {typeof(MainDbE.People.CheckEmployee_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.People.CheckEmployee_RequestProperty.EmployeeId,}},
            {typeof(MainDbE.People.DeleteCustomer_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.People.DeleteCustomer_RequestProperty.CustomerId,}},
            {typeof(MainDbE.People.DeleteEmployee_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.People.DeleteEmployee_RequestProperty.EmployeeId,}},
            {typeof(MainDbE.People.GetCustomer_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.People.GetCustomer_RequestProperty.CustomerId,}},
            {typeof(MainDbE.People.GetCustomersBySupportRep_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.People.GetCustomersBySupportRep_RequestProperty.SupportRepId,}},
            {typeof(MainDbE.People.GetEmployee_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.People.GetEmployee_RequestProperty.EmployeeId,}},
            {typeof(MainDbE.People.GetEmployeeReportsTo_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.People.GetEmployeeReportsTo_RequestProperty.EmployeeId,}},
            {typeof(MainDbE.People.GetEmployeesByReportsTo_RequestProperty).MetadataToken, new HashSet<int>(1){(int)MainDbE.People.GetEmployeesByReportsTo_RequestProperty.EmployeeId,}},
            {typeof(MainDbE.People.InsertCustomer_RequestProperty).MetadataToken, new HashSet<int>(13){(int)MainDbE.People.InsertCustomer_RequestProperty.FirstName,(int)MainDbE.People.InsertCustomer_RequestProperty.LastName,(int)MainDbE.People.InsertCustomer_RequestProperty.Company,(int)MainDbE.People.InsertCustomer_RequestProperty.Address,(int)MainDbE.People.InsertCustomer_RequestProperty.City,(int)MainDbE.People.InsertCustomer_RequestProperty.State,(int)MainDbE.People.InsertCustomer_RequestProperty.Country,(int)MainDbE.People.InsertCustomer_RequestProperty.PostalCode,(int)MainDbE.People.InsertCustomer_RequestProperty.Phone,(int)MainDbE.People.InsertCustomer_RequestProperty.Fax,(int)MainDbE.People.InsertCustomer_RequestProperty.Email,(int)MainDbE.People.InsertCustomer_RequestProperty.SupportRepId,(int)MainDbE.People.InsertCustomer_RequestProperty.CustomerId,}},
            {typeof(MainDbE.People.InsertEmployee_RequestProperty).MetadataToken, new HashSet<int>(15){(int)MainDbE.People.InsertEmployee_RequestProperty.LastName,(int)MainDbE.People.InsertEmployee_RequestProperty.FirstName,(int)MainDbE.People.InsertEmployee_RequestProperty.Title,(int)MainDbE.People.InsertEmployee_RequestProperty.ReportsTo,(int)MainDbE.People.InsertEmployee_RequestProperty.BirthDate,(int)MainDbE.People.InsertEmployee_RequestProperty.HireDate,(int)MainDbE.People.InsertEmployee_RequestProperty.Address,(int)MainDbE.People.InsertEmployee_RequestProperty.City,(int)MainDbE.People.InsertEmployee_RequestProperty.State,(int)MainDbE.People.InsertEmployee_RequestProperty.Country,(int)MainDbE.People.InsertEmployee_RequestProperty.PostalCode,(int)MainDbE.People.InsertEmployee_RequestProperty.Phone,(int)MainDbE.People.InsertEmployee_RequestProperty.Fax,(int)MainDbE.People.InsertEmployee_RequestProperty.Email,(int)MainDbE.People.InsertEmployee_RequestProperty.EmployeeId,}},
            {typeof(MainDbE.People.UpdateCustomer_RequestProperty).MetadataToken, new HashSet<int>(13){(int)MainDbE.People.UpdateCustomer_RequestProperty.CustomerId,(int)MainDbE.People.UpdateCustomer_RequestProperty.FirstName,(int)MainDbE.People.UpdateCustomer_RequestProperty.LastName,(int)MainDbE.People.UpdateCustomer_RequestProperty.Company,(int)MainDbE.People.UpdateCustomer_RequestProperty.Address,(int)MainDbE.People.UpdateCustomer_RequestProperty.City,(int)MainDbE.People.UpdateCustomer_RequestProperty.State,(int)MainDbE.People.UpdateCustomer_RequestProperty.Country,(int)MainDbE.People.UpdateCustomer_RequestProperty.PostalCode,(int)MainDbE.People.UpdateCustomer_RequestProperty.Phone,(int)MainDbE.People.UpdateCustomer_RequestProperty.Fax,(int)MainDbE.People.UpdateCustomer_RequestProperty.Email,(int)MainDbE.People.UpdateCustomer_RequestProperty.SupportRepId,}},
            {typeof(MainDbE.People.UpdateEmployee_RequestProperty).MetadataToken, new HashSet<int>(15){(int)MainDbE.People.UpdateEmployee_RequestProperty.EmployeeId,(int)MainDbE.People.UpdateEmployee_RequestProperty.LastName,(int)MainDbE.People.UpdateEmployee_RequestProperty.FirstName,(int)MainDbE.People.UpdateEmployee_RequestProperty.Title,(int)MainDbE.People.UpdateEmployee_RequestProperty.ReportsTo,(int)MainDbE.People.UpdateEmployee_RequestProperty.BirthDate,(int)MainDbE.People.UpdateEmployee_RequestProperty.HireDate,(int)MainDbE.People.UpdateEmployee_RequestProperty.Address,(int)MainDbE.People.UpdateEmployee_RequestProperty.City,(int)MainDbE.People.UpdateEmployee_RequestProperty.State,(int)MainDbE.People.UpdateEmployee_RequestProperty.Country,(int)MainDbE.People.UpdateEmployee_RequestProperty.PostalCode,(int)MainDbE.People.UpdateEmployee_RequestProperty.Phone,(int)MainDbE.People.UpdateEmployee_RequestProperty.Fax,(int)MainDbE.People.UpdateEmployee_RequestProperty.Email,}},
        };
        #endregion
        #region PropTypes
        internal static readonly Dictionary<int, Dictionary<int, Type>> PropTypes = new Dictionary<int, Dictionary<int, Type>>(93)
        {
            {typeof(MainDbE.Accounting.InvoiceProperty).MetadataToken, new Dictionary<int, Type>(9){ {(int)MainDbE.Accounting.InvoiceProperty.InvoiceId, typeof(int)}, {(int)MainDbE.Accounting.InvoiceProperty.CustomerId, typeof(int)}, {(int)MainDbE.Accounting.InvoiceProperty.InvoiceDate, typeof(DateTime)}, {(int)MainDbE.Accounting.InvoiceProperty.BillingAddress, typeof(string)}, {(int)MainDbE.Accounting.InvoiceProperty.BillingCity, typeof(string)}, {(int)MainDbE.Accounting.InvoiceProperty.BillingState, typeof(string)}, {(int)MainDbE.Accounting.InvoiceProperty.BillingCountry, typeof(string)}, {(int)MainDbE.Accounting.InvoiceProperty.BillingPostalCode, typeof(string)}, {(int)MainDbE.Accounting.InvoiceProperty.Total, typeof(decimal)},}},
            {typeof(MainDbE.Accounting.InvoiceLineProperty).MetadataToken, new Dictionary<int, Type>(5){ {(int)MainDbE.Accounting.InvoiceLineProperty.InvoiceLineId, typeof(int)}, {(int)MainDbE.Accounting.InvoiceLineProperty.InvoiceId, typeof(int)}, {(int)MainDbE.Accounting.InvoiceLineProperty.TrackId, typeof(int)}, {(int)MainDbE.Accounting.InvoiceLineProperty.UnitPrice, typeof(decimal)}, {(int)MainDbE.Accounting.InvoiceLineProperty.Quantity, typeof(int)},}},
            {typeof(MainDbE.Accounting.OrderDetailProperty).MetadataToken, new Dictionary<int, Type>(3){ {(int)MainDbE.Accounting.OrderDetailProperty.Id, typeof(int)}, {(int)MainDbE.Accounting.OrderDetailProperty.SubId, typeof(string)}, {(int)MainDbE.Accounting.OrderDetailProperty.Name, typeof(string)},}},
            {typeof(MainDbE.Media.AlbumProperty).MetadataToken, new Dictionary<int, Type>(3){ {(int)MainDbE.Media.AlbumProperty.AlbumId, typeof(int)}, {(int)MainDbE.Media.AlbumProperty.Title, typeof(string)}, {(int)MainDbE.Media.AlbumProperty.ArtistId, typeof(int)},}},
            {typeof(MainDbE.Media.ArtistProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.ArtistProperty.ArtistId, typeof(int)}, {(int)MainDbE.Media.ArtistProperty.Name, typeof(string)},}},
            {typeof(MainDbE.Media.GenreProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.GenreProperty.GenreId, typeof(int)}, {(int)MainDbE.Media.GenreProperty.Name, typeof(string)},}},
            {typeof(MainDbE.Media.MediaTypeProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.MediaTypeProperty.MediaTypeId, typeof(int)}, {(int)MainDbE.Media.MediaTypeProperty.Name, typeof(string)},}},
            {typeof(MainDbE.Media.PlaylistProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.PlaylistProperty.PlaylistId, typeof(int)}, {(int)MainDbE.Media.PlaylistProperty.Name, typeof(string)},}},
            {typeof(MainDbE.Media.PlaylistTrackProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.PlaylistTrackProperty.PlaylistId, typeof(int)}, {(int)MainDbE.Media.PlaylistTrackProperty.TrackId, typeof(int)},}},
            {typeof(MainDbE.Media.TrackProperty).MetadataToken, new Dictionary<int, Type>(9){ {(int)MainDbE.Media.TrackProperty.TrackId, typeof(int)}, {(int)MainDbE.Media.TrackProperty.Name, typeof(string)}, {(int)MainDbE.Media.TrackProperty.AlbumId, typeof(int)}, {(int)MainDbE.Media.TrackProperty.MediaTypeId, typeof(int)}, {(int)MainDbE.Media.TrackProperty.GenreId, typeof(int)}, {(int)MainDbE.Media.TrackProperty.Composer, typeof(string)}, {(int)MainDbE.Media.TrackProperty.Milliseconds, typeof(int)}, {(int)MainDbE.Media.TrackProperty.Bytes, typeof(int)}, {(int)MainDbE.Media.TrackProperty.UnitPrice, typeof(decimal)},}},
            {typeof(MainDbE.People.CustomerProperty).MetadataToken, new Dictionary<int, Type>(13){ {(int)MainDbE.People.CustomerProperty.CustomerId, typeof(int)}, {(int)MainDbE.People.CustomerProperty.FirstName, typeof(string)}, {(int)MainDbE.People.CustomerProperty.LastName, typeof(string)}, {(int)MainDbE.People.CustomerProperty.Company, typeof(string)}, {(int)MainDbE.People.CustomerProperty.Address, typeof(string)}, {(int)MainDbE.People.CustomerProperty.City, typeof(string)}, {(int)MainDbE.People.CustomerProperty.State, typeof(string)}, {(int)MainDbE.People.CustomerProperty.Country, typeof(string)}, {(int)MainDbE.People.CustomerProperty.PostalCode, typeof(string)}, {(int)MainDbE.People.CustomerProperty.Phone, typeof(string)}, {(int)MainDbE.People.CustomerProperty.Fax, typeof(string)}, {(int)MainDbE.People.CustomerProperty.Email, typeof(string)}, {(int)MainDbE.People.CustomerProperty.SupportRepId, typeof(int)},}},
            {typeof(MainDbE.People.EmployeeProperty).MetadataToken, new Dictionary<int, Type>(15){ {(int)MainDbE.People.EmployeeProperty.EmployeeId, typeof(int)}, {(int)MainDbE.People.EmployeeProperty.LastName, typeof(string)}, {(int)MainDbE.People.EmployeeProperty.FirstName, typeof(string)}, {(int)MainDbE.People.EmployeeProperty.Title, typeof(string)}, {(int)MainDbE.People.EmployeeProperty.ReportsTo, typeof(int)}, {(int)MainDbE.People.EmployeeProperty.BirthDate, typeof(DateTime)}, {(int)MainDbE.People.EmployeeProperty.HireDate, typeof(DateTime)}, {(int)MainDbE.People.EmployeeProperty.Address, typeof(string)}, {(int)MainDbE.People.EmployeeProperty.City, typeof(string)}, {(int)MainDbE.People.EmployeeProperty.State, typeof(string)}, {(int)MainDbE.People.EmployeeProperty.Country, typeof(string)}, {(int)MainDbE.People.EmployeeProperty.PostalCode, typeof(string)}, {(int)MainDbE.People.EmployeeProperty.Phone, typeof(string)}, {(int)MainDbE.People.EmployeeProperty.Fax, typeof(string)}, {(int)MainDbE.People.EmployeeProperty.Email, typeof(string)},}},
            {typeof(MainDbE.Accounting.CheckInvoice_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Accounting.CheckInvoice_RequestProperty.InvoiceId, typeof(int)},}},
            {typeof(MainDbE.Accounting.CheckInvoiceLine_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Accounting.CheckInvoiceLine_RequestProperty.InvoiceLineId, typeof(int)},}},
            {typeof(MainDbE.Accounting.DeleteInvoice_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Accounting.DeleteInvoice_RequestProperty.InvoiceId, typeof(int)},}},
            {typeof(MainDbE.Accounting.DeleteInvoiceLine_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Accounting.DeleteInvoiceLine_RequestProperty.InvoiceLineId, typeof(int)},}},
            {typeof(MainDbE.Accounting.GetInvoice_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Accounting.GetInvoice_RequestProperty.InvoiceId, typeof(int)},}},
            {typeof(MainDbE.Accounting.GetInvoiceLine_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Accounting.GetInvoiceLine_RequestProperty.InvoiceLineId, typeof(int)},}},
            {typeof(MainDbE.Accounting.GetInvoiceLinesByInvoice_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Accounting.GetInvoiceLinesByInvoice_RequestProperty.InvoiceId, typeof(int)},}},
            {typeof(MainDbE.Accounting.GetInvoiceLinesByTrack_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Accounting.GetInvoiceLinesByTrack_RequestProperty.TrackId, typeof(int)},}},
            {typeof(MainDbE.Accounting.GetInvoicesByCustomer_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Accounting.GetInvoicesByCustomer_RequestProperty.CustomerId, typeof(int)},}},
            {typeof(MainDbE.Accounting.GetInvoicesByEmployee_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Accounting.GetInvoicesByEmployee_RequestProperty.EmployeeId, typeof(int)},}},
            {typeof(MainDbE.Accounting.InsertInvoice_RequestProperty).MetadataToken, new Dictionary<int, Type>(9){ {(int)MainDbE.Accounting.InsertInvoice_RequestProperty.CustomerId, typeof(int)}, {(int)MainDbE.Accounting.InsertInvoice_RequestProperty.InvoiceDate, typeof(DateTime)}, {(int)MainDbE.Accounting.InsertInvoice_RequestProperty.BillingAddress, typeof(string)}, {(int)MainDbE.Accounting.InsertInvoice_RequestProperty.BillingCity, typeof(string)}, {(int)MainDbE.Accounting.InsertInvoice_RequestProperty.BillingState, typeof(string)}, {(int)MainDbE.Accounting.InsertInvoice_RequestProperty.BillingCountry, typeof(string)}, {(int)MainDbE.Accounting.InsertInvoice_RequestProperty.BillingPostalCode, typeof(string)}, {(int)MainDbE.Accounting.InsertInvoice_RequestProperty.Total, typeof(decimal)}, {(int)MainDbE.Accounting.InsertInvoice_RequestProperty.InvoiceId, typeof(int)},}},
            {typeof(MainDbE.Accounting.InsertInvoiceLine_RequestProperty).MetadataToken, new Dictionary<int, Type>(5){ {(int)MainDbE.Accounting.InsertInvoiceLine_RequestProperty.InvoiceId, typeof(int)}, {(int)MainDbE.Accounting.InsertInvoiceLine_RequestProperty.TrackId, typeof(int)}, {(int)MainDbE.Accounting.InsertInvoiceLine_RequestProperty.UnitPrice, typeof(decimal)}, {(int)MainDbE.Accounting.InsertInvoiceLine_RequestProperty.Quantity, typeof(int)}, {(int)MainDbE.Accounting.InsertInvoiceLine_RequestProperty.InvoiceLineId, typeof(int)},}},
            {typeof(MainDbE.Accounting.UpdateInvoice_RequestProperty).MetadataToken, new Dictionary<int, Type>(9){ {(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.InvoiceId, typeof(int)}, {(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.CustomerId, typeof(int)}, {(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.InvoiceDate, typeof(DateTime)}, {(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.BillingAddress, typeof(string)}, {(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.BillingCity, typeof(string)}, {(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.BillingState, typeof(string)}, {(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.BillingCountry, typeof(string)}, {(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.BillingPostalCode, typeof(string)}, {(int)MainDbE.Accounting.UpdateInvoice_RequestProperty.Total, typeof(decimal)},}},
            {typeof(MainDbE.Accounting.UpdateInvoiceLine_RequestProperty).MetadataToken, new Dictionary<int, Type>(5){ {(int)MainDbE.Accounting.UpdateInvoiceLine_RequestProperty.InvoiceLineId, typeof(int)}, {(int)MainDbE.Accounting.UpdateInvoiceLine_RequestProperty.InvoiceId, typeof(int)}, {(int)MainDbE.Accounting.UpdateInvoiceLine_RequestProperty.TrackId, typeof(int)}, {(int)MainDbE.Accounting.UpdateInvoiceLine_RequestProperty.UnitPrice, typeof(decimal)}, {(int)MainDbE.Accounting.UpdateInvoiceLine_RequestProperty.Quantity, typeof(int)},}},
            {typeof(MainDbE.Media.CheckAlbum_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.CheckAlbum_RequestProperty.AlbumId, typeof(int)},}},
            {typeof(MainDbE.Media.CheckArtist_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.CheckArtist_RequestProperty.ArtistId, typeof(int)},}},
            {typeof(MainDbE.Media.CheckGenre_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.CheckGenre_RequestProperty.GenreId, typeof(int)},}},
            {typeof(MainDbE.Media.CheckMediaType_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.CheckMediaType_RequestProperty.MediaTypeId, typeof(int)},}},
            {typeof(MainDbE.Media.CheckPlaylist_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.CheckPlaylist_RequestProperty.PlaylistId, typeof(int)},}},
            {typeof(MainDbE.Media.CheckPlaylistTrack_RequestProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.CheckPlaylistTrack_RequestProperty.PlaylistId, typeof(int)}, {(int)MainDbE.Media.CheckPlaylistTrack_RequestProperty.TrackId, typeof(int)},}},
            {typeof(MainDbE.Media.CheckTrack_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.CheckTrack_RequestProperty.TrackId, typeof(int)},}},
            {typeof(MainDbE.Media.DeleteAlbum_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.DeleteAlbum_RequestProperty.AlbumId, typeof(int)},}},
            {typeof(MainDbE.Media.DeleteArtist_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.DeleteArtist_RequestProperty.ArtistId, typeof(int)},}},
            {typeof(MainDbE.Media.DeleteGenre_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.DeleteGenre_RequestProperty.GenreId, typeof(int)},}},
            {typeof(MainDbE.Media.DeleteMediaType_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.DeleteMediaType_RequestProperty.MediaTypeId, typeof(int)},}},
            {typeof(MainDbE.Media.DeletePlaylist_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.DeletePlaylist_RequestProperty.PlaylistId, typeof(int)},}},
            {typeof(MainDbE.Media.DeletePlaylistTrack_RequestProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.DeletePlaylistTrack_RequestProperty.PlaylistId, typeof(int)}, {(int)MainDbE.Media.DeletePlaylistTrack_RequestProperty.TrackId, typeof(int)},}},
            {typeof(MainDbE.Media.DeleteTrack_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.DeleteTrack_RequestProperty.TrackId, typeof(int)},}},
            {typeof(MainDbE.Media.GetAlbum_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.GetAlbum_RequestProperty.AlbumId, typeof(int)},}},
            {typeof(MainDbE.Media.GetAlbumsByArtist_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.GetAlbumsByArtist_RequestProperty.ArtistId, typeof(int)},}},
            {typeof(MainDbE.Media.GetArtist_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.GetArtist_RequestProperty.ArtistId, typeof(int)},}},
            {typeof(MainDbE.Media.GetGenre_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.GetGenre_RequestProperty.GenreId, typeof(int)},}},
            {typeof(MainDbE.Media.GetMediaType_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.GetMediaType_RequestProperty.MediaTypeId, typeof(int)},}},
            {typeof(MainDbE.Media.GetPlaylist_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.GetPlaylist_RequestProperty.PlaylistId, typeof(int)},}},
            {typeof(MainDbE.Media.GetPlaylistsByTrack_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.GetPlaylistsByTrack_RequestProperty.TrackId, typeof(int)},}},
            {typeof(MainDbE.Media.GetPlaylistTrack_RequestProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.GetPlaylistTrack_RequestProperty.PlaylistId, typeof(int)}, {(int)MainDbE.Media.GetPlaylistTrack_RequestProperty.TrackId, typeof(int)},}},
            {typeof(MainDbE.Media.GetTrack_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.GetTrack_RequestProperty.TrackId, typeof(int)},}},
            {typeof(MainDbE.Media.GetTracksByAlbum_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.GetTracksByAlbum_RequestProperty.AlbumId, typeof(int)},}},
            {typeof(MainDbE.Media.GetTracksByArtist_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.GetTracksByArtist_RequestProperty.ArtistId, typeof(int)},}},
            {typeof(MainDbE.Media.GetTracksByGenre_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.GetTracksByGenre_RequestProperty.GenreId, typeof(int)},}},
            {typeof(MainDbE.Media.GetTracksByInvoice_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.GetTracksByInvoice_RequestProperty.InvoiceId, typeof(int)},}},
            {typeof(MainDbE.Media.GetTracksByMediaType_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.GetTracksByMediaType_RequestProperty.MediaTypeId, typeof(int)},}},
            {typeof(MainDbE.Media.GetTracksByPlaylist_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.Media.GetTracksByPlaylist_RequestProperty.PlaylistId, typeof(int)},}},
            {typeof(MainDbE.Media.InsertAlbum_RequestProperty).MetadataToken, new Dictionary<int, Type>(3){ {(int)MainDbE.Media.InsertAlbum_RequestProperty.Title, typeof(string)}, {(int)MainDbE.Media.InsertAlbum_RequestProperty.ArtistId, typeof(int)}, {(int)MainDbE.Media.InsertAlbum_RequestProperty.AlbumId, typeof(int)},}},
            {typeof(MainDbE.Media.InsertArtist_RequestProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.InsertArtist_RequestProperty.Name, typeof(string)}, {(int)MainDbE.Media.InsertArtist_RequestProperty.ArtistId, typeof(int)},}},
            {typeof(MainDbE.Media.InsertGenre_RequestProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.InsertGenre_RequestProperty.Name, typeof(string)}, {(int)MainDbE.Media.InsertGenre_RequestProperty.GenreId, typeof(int)},}},
            {typeof(MainDbE.Media.InsertMediaType_RequestProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.InsertMediaType_RequestProperty.Name, typeof(string)}, {(int)MainDbE.Media.InsertMediaType_RequestProperty.MediaTypeId, typeof(int)},}},
            {typeof(MainDbE.Media.InsertPlaylist_RequestProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.InsertPlaylist_RequestProperty.Name, typeof(string)}, {(int)MainDbE.Media.InsertPlaylist_RequestProperty.PlaylistId, typeof(int)},}},
            {typeof(MainDbE.Media.InsertPlaylistTrack_RequestProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.InsertPlaylistTrack_RequestProperty.PlaylistId, typeof(int)}, {(int)MainDbE.Media.InsertPlaylistTrack_RequestProperty.TrackId, typeof(int)},}},
            {typeof(MainDbE.Media.InsertTrack_RequestProperty).MetadataToken, new Dictionary<int, Type>(9){ {(int)MainDbE.Media.InsertTrack_RequestProperty.Name, typeof(string)}, {(int)MainDbE.Media.InsertTrack_RequestProperty.AlbumId, typeof(int)}, {(int)MainDbE.Media.InsertTrack_RequestProperty.MediaTypeId, typeof(int)}, {(int)MainDbE.Media.InsertTrack_RequestProperty.GenreId, typeof(int)}, {(int)MainDbE.Media.InsertTrack_RequestProperty.Composer, typeof(string)}, {(int)MainDbE.Media.InsertTrack_RequestProperty.Milliseconds, typeof(int)}, {(int)MainDbE.Media.InsertTrack_RequestProperty.Bytes, typeof(int)}, {(int)MainDbE.Media.InsertTrack_RequestProperty.UnitPrice, typeof(decimal)}, {(int)MainDbE.Media.InsertTrack_RequestProperty.TrackId, typeof(int)},}},
            {typeof(MainDbE.Media.UpdateAlbum_RequestProperty).MetadataToken, new Dictionary<int, Type>(3){ {(int)MainDbE.Media.UpdateAlbum_RequestProperty.AlbumId, typeof(int)}, {(int)MainDbE.Media.UpdateAlbum_RequestProperty.Title, typeof(string)}, {(int)MainDbE.Media.UpdateAlbum_RequestProperty.ArtistId, typeof(int)},}},
            {typeof(MainDbE.Media.UpdateArtist_RequestProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.UpdateArtist_RequestProperty.ArtistId, typeof(int)}, {(int)MainDbE.Media.UpdateArtist_RequestProperty.Name, typeof(string)},}},
            {typeof(MainDbE.Media.UpdateGenre_RequestProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.UpdateGenre_RequestProperty.GenreId, typeof(int)}, {(int)MainDbE.Media.UpdateGenre_RequestProperty.Name, typeof(string)},}},
            {typeof(MainDbE.Media.UpdateMediaType_RequestProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.UpdateMediaType_RequestProperty.MediaTypeId, typeof(int)}, {(int)MainDbE.Media.UpdateMediaType_RequestProperty.Name, typeof(string)},}},
            {typeof(MainDbE.Media.UpdatePlaylist_RequestProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.UpdatePlaylist_RequestProperty.PlaylistId, typeof(int)}, {(int)MainDbE.Media.UpdatePlaylist_RequestProperty.Name, typeof(string)},}},
            {typeof(MainDbE.Media.UpdatePlaylistTrack_RequestProperty).MetadataToken, new Dictionary<int, Type>(2){ {(int)MainDbE.Media.UpdatePlaylistTrack_RequestProperty.PlaylistId, typeof(int)}, {(int)MainDbE.Media.UpdatePlaylistTrack_RequestProperty.TrackId, typeof(int)},}},
            {typeof(MainDbE.Media.UpdateTrack_RequestProperty).MetadataToken, new Dictionary<int, Type>(9){ {(int)MainDbE.Media.UpdateTrack_RequestProperty.TrackId, typeof(int)}, {(int)MainDbE.Media.UpdateTrack_RequestProperty.Name, typeof(string)}, {(int)MainDbE.Media.UpdateTrack_RequestProperty.AlbumId, typeof(int)}, {(int)MainDbE.Media.UpdateTrack_RequestProperty.MediaTypeId, typeof(int)}, {(int)MainDbE.Media.UpdateTrack_RequestProperty.GenreId, typeof(int)}, {(int)MainDbE.Media.UpdateTrack_RequestProperty.Composer, typeof(string)}, {(int)MainDbE.Media.UpdateTrack_RequestProperty.Milliseconds, typeof(int)}, {(int)MainDbE.Media.UpdateTrack_RequestProperty.Bytes, typeof(int)}, {(int)MainDbE.Media.UpdateTrack_RequestProperty.UnitPrice, typeof(decimal)},}},
            {typeof(MainDbE.People.CheckCustomer_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.People.CheckCustomer_RequestProperty.CustomerId, typeof(int)},}},
            {typeof(MainDbE.People.CheckEmployee_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.People.CheckEmployee_RequestProperty.EmployeeId, typeof(int)},}},
            {typeof(MainDbE.People.DeleteCustomer_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.People.DeleteCustomer_RequestProperty.CustomerId, typeof(int)},}},
            {typeof(MainDbE.People.DeleteEmployee_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.People.DeleteEmployee_RequestProperty.EmployeeId, typeof(int)},}},
            {typeof(MainDbE.People.GetCustomer_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.People.GetCustomer_RequestProperty.CustomerId, typeof(int)},}},
            {typeof(MainDbE.People.GetCustomersBySupportRep_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.People.GetCustomersBySupportRep_RequestProperty.SupportRepId, typeof(int)},}},
            {typeof(MainDbE.People.GetEmployee_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.People.GetEmployee_RequestProperty.EmployeeId, typeof(int)},}},
            {typeof(MainDbE.People.GetEmployeeReportsTo_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.People.GetEmployeeReportsTo_RequestProperty.EmployeeId, typeof(int)},}},
            {typeof(MainDbE.People.GetEmployeesByReportsTo_RequestProperty).MetadataToken, new Dictionary<int, Type>(1){ {(int)MainDbE.People.GetEmployeesByReportsTo_RequestProperty.EmployeeId, typeof(int)},}},
            {typeof(MainDbE.People.InsertCustomer_RequestProperty).MetadataToken, new Dictionary<int, Type>(13){ {(int)MainDbE.People.InsertCustomer_RequestProperty.FirstName, typeof(string)}, {(int)MainDbE.People.InsertCustomer_RequestProperty.LastName, typeof(string)}, {(int)MainDbE.People.InsertCustomer_RequestProperty.Company, typeof(string)}, {(int)MainDbE.People.InsertCustomer_RequestProperty.Address, typeof(string)}, {(int)MainDbE.People.InsertCustomer_RequestProperty.City, typeof(string)}, {(int)MainDbE.People.InsertCustomer_RequestProperty.State, typeof(string)}, {(int)MainDbE.People.InsertCustomer_RequestProperty.Country, typeof(string)}, {(int)MainDbE.People.InsertCustomer_RequestProperty.PostalCode, typeof(string)}, {(int)MainDbE.People.InsertCustomer_RequestProperty.Phone, typeof(string)}, {(int)MainDbE.People.InsertCustomer_RequestProperty.Fax, typeof(string)}, {(int)MainDbE.People.InsertCustomer_RequestProperty.Email, typeof(string)}, {(int)MainDbE.People.InsertCustomer_RequestProperty.SupportRepId, typeof(int)}, {(int)MainDbE.People.InsertCustomer_RequestProperty.CustomerId, typeof(int)},}},
            {typeof(MainDbE.People.InsertEmployee_RequestProperty).MetadataToken, new Dictionary<int, Type>(15){ {(int)MainDbE.People.InsertEmployee_RequestProperty.LastName, typeof(string)}, {(int)MainDbE.People.InsertEmployee_RequestProperty.FirstName, typeof(string)}, {(int)MainDbE.People.InsertEmployee_RequestProperty.Title, typeof(string)}, {(int)MainDbE.People.InsertEmployee_RequestProperty.ReportsTo, typeof(int)}, {(int)MainDbE.People.InsertEmployee_RequestProperty.BirthDate, typeof(DateTime)}, {(int)MainDbE.People.InsertEmployee_RequestProperty.HireDate, typeof(DateTime)}, {(int)MainDbE.People.InsertEmployee_RequestProperty.Address, typeof(string)}, {(int)MainDbE.People.InsertEmployee_RequestProperty.City, typeof(string)}, {(int)MainDbE.People.InsertEmployee_RequestProperty.State, typeof(string)}, {(int)MainDbE.People.InsertEmployee_RequestProperty.Country, typeof(string)}, {(int)MainDbE.People.InsertEmployee_RequestProperty.PostalCode, typeof(string)}, {(int)MainDbE.People.InsertEmployee_RequestProperty.Phone, typeof(string)}, {(int)MainDbE.People.InsertEmployee_RequestProperty.Fax, typeof(string)}, {(int)MainDbE.People.InsertEmployee_RequestProperty.Email, typeof(string)}, {(int)MainDbE.People.InsertEmployee_RequestProperty.EmployeeId, typeof(int)},}},
            {typeof(MainDbE.People.UpdateCustomer_RequestProperty).MetadataToken, new Dictionary<int, Type>(13){ {(int)MainDbE.People.UpdateCustomer_RequestProperty.CustomerId, typeof(int)}, {(int)MainDbE.People.UpdateCustomer_RequestProperty.FirstName, typeof(string)}, {(int)MainDbE.People.UpdateCustomer_RequestProperty.LastName, typeof(string)}, {(int)MainDbE.People.UpdateCustomer_RequestProperty.Company, typeof(string)}, {(int)MainDbE.People.UpdateCustomer_RequestProperty.Address, typeof(string)}, {(int)MainDbE.People.UpdateCustomer_RequestProperty.City, typeof(string)}, {(int)MainDbE.People.UpdateCustomer_RequestProperty.State, typeof(string)}, {(int)MainDbE.People.UpdateCustomer_RequestProperty.Country, typeof(string)}, {(int)MainDbE.People.UpdateCustomer_RequestProperty.PostalCode, typeof(string)}, {(int)MainDbE.People.UpdateCustomer_RequestProperty.Phone, typeof(string)}, {(int)MainDbE.People.UpdateCustomer_RequestProperty.Fax, typeof(string)}, {(int)MainDbE.People.UpdateCustomer_RequestProperty.Email, typeof(string)}, {(int)MainDbE.People.UpdateCustomer_RequestProperty.SupportRepId, typeof(int)},}},
            {typeof(MainDbE.People.UpdateEmployee_RequestProperty).MetadataToken, new Dictionary<int, Type>(15){ {(int)MainDbE.People.UpdateEmployee_RequestProperty.EmployeeId, typeof(int)}, {(int)MainDbE.People.UpdateEmployee_RequestProperty.LastName, typeof(string)}, {(int)MainDbE.People.UpdateEmployee_RequestProperty.FirstName, typeof(string)}, {(int)MainDbE.People.UpdateEmployee_RequestProperty.Title, typeof(string)}, {(int)MainDbE.People.UpdateEmployee_RequestProperty.ReportsTo, typeof(int)}, {(int)MainDbE.People.UpdateEmployee_RequestProperty.BirthDate, typeof(DateTime)}, {(int)MainDbE.People.UpdateEmployee_RequestProperty.HireDate, typeof(DateTime)}, {(int)MainDbE.People.UpdateEmployee_RequestProperty.Address, typeof(string)}, {(int)MainDbE.People.UpdateEmployee_RequestProperty.City, typeof(string)}, {(int)MainDbE.People.UpdateEmployee_RequestProperty.State, typeof(string)}, {(int)MainDbE.People.UpdateEmployee_RequestProperty.Country, typeof(string)}, {(int)MainDbE.People.UpdateEmployee_RequestProperty.PostalCode, typeof(string)}, {(int)MainDbE.People.UpdateEmployee_RequestProperty.Phone, typeof(string)}, {(int)MainDbE.People.UpdateEmployee_RequestProperty.Fax, typeof(string)}, {(int)MainDbE.People.UpdateEmployee_RequestProperty.Email, typeof(string)},}},
        };
        #endregion
        #region BinaryProps
        internal static readonly Dictionary<int, HashSet<int>> BinaryProps = new Dictionary<int, HashSet<int>>(93)
        {
            {typeof(MainDbE.Accounting.InvoiceProperty).MetadataToken, new HashSet<int>(9){}},
            {typeof(MainDbE.Accounting.InvoiceLineProperty).MetadataToken, new HashSet<int>(5){}},
            {typeof(MainDbE.Accounting.OrderDetailProperty).MetadataToken, new HashSet<int>(3){}},
            {typeof(MainDbE.Media.AlbumProperty).MetadataToken, new HashSet<int>(3){}},
            {typeof(MainDbE.Media.ArtistProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.GenreProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.MediaTypeProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.PlaylistProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.PlaylistTrackProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.TrackProperty).MetadataToken, new HashSet<int>(9){}},
            {typeof(MainDbE.People.CustomerProperty).MetadataToken, new HashSet<int>(13){}},
            {typeof(MainDbE.People.EmployeeProperty).MetadataToken, new HashSet<int>(15){}},
            {typeof(MainDbE.Accounting.CheckInvoice_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Accounting.CheckInvoiceLine_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Accounting.DeleteInvoice_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Accounting.DeleteInvoiceLine_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Accounting.GetInvoice_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Accounting.GetInvoiceLine_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Accounting.GetInvoiceLinesByInvoice_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Accounting.GetInvoiceLinesByTrack_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Accounting.GetInvoicesByCustomer_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Accounting.GetInvoicesByEmployee_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Accounting.InsertInvoice_RequestProperty).MetadataToken, new HashSet<int>(9){}},
            {typeof(MainDbE.Accounting.InsertInvoiceLine_RequestProperty).MetadataToken, new HashSet<int>(5){}},
            {typeof(MainDbE.Accounting.UpdateInvoice_RequestProperty).MetadataToken, new HashSet<int>(9){}},
            {typeof(MainDbE.Accounting.UpdateInvoiceLine_RequestProperty).MetadataToken, new HashSet<int>(5){}},
            {typeof(MainDbE.Media.CheckAlbum_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.CheckArtist_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.CheckGenre_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.CheckMediaType_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.CheckPlaylist_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.CheckPlaylistTrack_RequestProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.CheckTrack_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.DeleteAlbum_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.DeleteArtist_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.DeleteGenre_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.DeleteMediaType_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.DeletePlaylist_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.DeletePlaylistTrack_RequestProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.DeleteTrack_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.GetAlbum_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.GetAlbumsByArtist_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.GetArtist_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.GetGenre_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.GetMediaType_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.GetPlaylist_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.GetPlaylistsByTrack_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.GetPlaylistTrack_RequestProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.GetTrack_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.GetTracksByAlbum_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.GetTracksByArtist_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.GetTracksByGenre_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.GetTracksByInvoice_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.GetTracksByMediaType_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.GetTracksByPlaylist_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.Media.InsertAlbum_RequestProperty).MetadataToken, new HashSet<int>(3){}},
            {typeof(MainDbE.Media.InsertArtist_RequestProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.InsertGenre_RequestProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.InsertMediaType_RequestProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.InsertPlaylist_RequestProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.InsertPlaylistTrack_RequestProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.InsertTrack_RequestProperty).MetadataToken, new HashSet<int>(9){}},
            {typeof(MainDbE.Media.UpdateAlbum_RequestProperty).MetadataToken, new HashSet<int>(3){}},
            {typeof(MainDbE.Media.UpdateArtist_RequestProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.UpdateGenre_RequestProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.UpdateMediaType_RequestProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.UpdatePlaylist_RequestProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.UpdatePlaylistTrack_RequestProperty).MetadataToken, new HashSet<int>(2){}},
            {typeof(MainDbE.Media.UpdateTrack_RequestProperty).MetadataToken, new HashSet<int>(9){}},
            {typeof(MainDbE.People.CheckCustomer_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.People.CheckEmployee_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.People.DeleteCustomer_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.People.DeleteEmployee_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.People.GetCustomer_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.People.GetCustomersBySupportRep_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.People.GetEmployee_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.People.GetEmployeeReportsTo_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.People.GetEmployeesByReportsTo_RequestProperty).MetadataToken, new HashSet<int>(1){}},
            {typeof(MainDbE.People.InsertCustomer_RequestProperty).MetadataToken, new HashSet<int>(13){}},
            {typeof(MainDbE.People.InsertEmployee_RequestProperty).MetadataToken, new HashSet<int>(15){}},
            {typeof(MainDbE.People.UpdateCustomer_RequestProperty).MetadataToken, new HashSet<int>(13){}},
            {typeof(MainDbE.People.UpdateEmployee_RequestProperty).MetadataToken, new HashSet<int>(15){}},
        };
        #endregion
    }
}
